version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development